apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: admin-auth
  namespace: default
spec:
  forwardAuth:
    address: http://{{ include "helm.fullname" . }}:{{ .Values.service.port }}/auth
