replicaCount: 1

image:
  repository: frikanalen/admin-auth-service
  tag: latest
  pullPolicy: Always

env: "production"

resources: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hostname: "admin.frikanalen.no"
  tls: true

prometheusRule:
  enabled: true