replicaCount: 1

image:
  repository: frikanalen/admin-auth-service
  tag: latest
  pullPolicy: Always

env: "production"
loginUrl: "https://login.admin.frikanalen.no"

resources: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  hostname: "login.admin.frikanalen.no"

#secretKey: ""
